import { AutoGenerated } from 'src/core/decorators/auto-generated.decorator';
import { BaseEntity } from 'src/core/typeorm/entities/base.entity';
import { autoSlug } from 'src/core/typeorm/listeners/auto-slug.listener';
import {
  BeforeInsert,
  BeforeUpdate,
  Column,
  Entity,
  PrimaryGeneratedColumn,
} from 'typeorm';

@Entity()
export class Author extends BaseEntity {
  @PrimaryGeneratedColumn()
  @AutoGenerated()
  id: number;

  @Column({ nullable: false, unique: true })
  name: string;

  @Column({ nullable: false })
  @AutoGenerated()
  slug: string;

  @BeforeInsert()
  @BeforeUpdate()
  handleAutoSlug() {
    autoSlug(this, { field: 'name' });
  }
}
