import { AutoGenerated } from 'src/core/decorators/auto-generated.decorator';
import { Disabled } from 'src/core/decorators/disabled.decorator';
import { RichText } from 'src/core/decorators/rich-text.decorator';
import { Select } from 'src/core/decorators/select.decorator';
import { BaseEntity } from 'src/core/typeorm/entities/base.entity';
import { Column, Entity, PrimaryGeneratedColumn } from 'typeorm';

export enum LogLevel {
  WARN = 'warn',
  ERROR = 'error',
}

@Entity()
export class Logs extends BaseEntity {
  @PrimaryGeneratedColumn()
  @AutoGenerated()
  id: number;

  @Column({ nullable: false, type: 'varchar' })
  @Disabled()
  @Select()
  level: LogLevel;

  @Column({ nullable: false, type: 'varchar' })
  @Disabled()
  message: string;

  @Column({ nullable: false })
  @Disabled()
  @RichText()
  context: string;
}
