import { Author } from 'src/author/entities/author.entity';
import { Category } from 'src/category/entities/category.entity';
import { AutoGenerated } from 'src/core/decorators/auto-generated.decorator';
import { Disabled } from 'src/core/decorators/disabled.decorator';
import { Required } from 'src/core/decorators/required.decorator';
import { RichText } from 'src/core/decorators/rich-text.decorator';
import { BaseEntity } from 'src/core/typeorm/entities/base.entity';
import {
  Column,
  Entity,
  Index,
  JoinColumn,
  JoinTable,
  ManyToMany,
  ManyToOne,
  PrimaryGeneratedColumn,
} from 'typeorm';

export enum StatusType {
  CONTINUE = 'Đang ra',
  FULL = 'Full',
}

@Entity()
@Index(['author'])
export class Story extends BaseEntity {
  @PrimaryGeneratedColumn()
  @AutoGenerated()
  id: number;

  @Column({ nullable: false })
  title: string;

  @Column({ nullable: false })
  @AutoGenerated()
  slug: string;

  @Column({ nullable: false })
  @RichText()
  description: string;

  @Column({ default: 0 })
  @Disabled()
  view: number;

  @Column({ default: 'Sưu tầm' })
  source: string;

  @Column({ default: StatusType.CONTINUE, type: 'varchar' })
  status: StatusType;

  @Column({ default: null })
  cover: string | null;

  @ManyToOne(() => Author, (author) => author.id, { nullable: false })
  @JoinColumn()
  author: Author;

  @Required()
  @ManyToMany(() => Category, { cascade: true, eager: true, nullable: false })
  @JoinTable()
  categories: Category[];
}
